# Generated by Django 4.0.1 on 2022-01-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'verbose_name': 'Aftor', 'verbose_name_plural': 'Aftor'},
        ),
    ]
